//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePartner_App_Mid.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string Ad_Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Dob { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Security_key { get; set; }
        public string Gender { get; set; }
        public string Nid { get; set; }
        public string Password { get; set; }
        public string Img { get; set; }
    }
}
