//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePartner_App_Mid.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        public int PostId { get; set; }
        public string En_Post_Email { get; set; }
        public string In_Asp_Email { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Post_Time { get; set; }
        public int Asking_Amount { get; set; }
        public double Asking_Share { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public Nullable<int> Offer_Amount { get; set; }
        public Nullable<double> Offer_Share { get; set; }
        public string Img { get; set; }
    
        public virtual Entrepreneur Entrepreneur { get; set; }
        public virtual Investor Investor { get; set; }
    }
}
