//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePartner_App_Mid.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_Investors
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Dob { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Nid { get; set; }
        public string OrgName { get; set; }
        public Nullable<System.DateTime> OrgEstablished { get; set; }
        public string OrgLocation { get; set; }
        public string OrgEmail { get; set; }
        public string OrgPhone { get; set; }
        public string OrgLicense { get; set; }
        public string Tin { get; set; }
        public string OrgSite { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public string EmailValidation { get; set; }
    }
}
