//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePartner_App_Mid.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MsgId { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Message1 { get; set; }
        public string Status { get; set; }
        public string Time { get; set; }
    }
}
