//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BePartner_App_Mid.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string Task_Description { get; set; }
        public System.DateTime Issue_time { get; set; }
        public System.DateTime Due_time { get; set; }
        public string Status { get; set; }
        public string Subject { get; set; }
    }
}
